<?php

return [
    'catalog' => [
        'view.dashboard' => [
            'name' => 'Ver inicio',
            'group' => 'General',
            'description' => 'Permite acceder al dashboard principal del sistema.',
            'default_profiles' => ['Admin', 'Sales'],
            'route_names' => ['dashboard'],
        ],
        'view.admin.preregistrations' => [
            'name' => 'Ver preregistros',
            'group' => 'Administracion',
            'description' => 'Permite acceder al modulo de preregistros.',
            'default_profiles' => ['Admin', 'Sales'],
            'route_names' => ['preregistrations'],
        ],
        'view.admin.policies' => [
            'name' => 'Ver membresias',
            'group' => 'Administracion',
            'description' => 'Permite acceder al catalogo principal de membresias.',
            'default_profiles' => ['Admin', 'Sales'],
            'route_names' => ['policies'],
        ],
        'view.admin.appointments' => [
            'name' => 'Ver citas',
            'group' => 'Administracion',
            'description' => 'Permite acceder al modulo administrativo de citas.',
            'default_profiles' => ['Admin'],
            'route_names' => ['appointments'],
        ],
        'view.admin.doctors' => [
            'name' => 'Ver red',
            'group' => 'Administracion',
            'description' => 'Permite acceder al catalogo de red y proveedores.',
            'default_profiles' => ['Admin'],
            'route_names' => ['doctors'],
        ],
        'view.admin.users' => [
            'name' => 'Ver usuarios',
            'group' => 'Administracion',
            'description' => 'Permite acceder a la administracion de usuarios.',
            'default_profiles' => ['Admin'],
            'route_names' => ['users'],
        ],
        'view.admin.whatsapp_console' => [
            'name' => 'Ver consola WhatsApp',
            'group' => 'Administracion',
            'description' => 'Permite acceder a la consola de conversaciones de WhatsApp.',
            'default_profiles' => ['Admin'],
            'route_names' => ['whatsapp.console'],
        ],
        'view.reports.commissions' => [
            'name' => 'Ver reporte de comisiones',
            'group' => 'Reportes',
            'description' => 'Permite acceder al reporte de comisiones.',
            'default_profiles' => ['Admin'],
            'route_names' => ['reports.commissions'],
        ],
        'view.reports.sales' => [
            'name' => 'Ver reporte de ventas',
            'group' => 'Reportes',
            'description' => 'Permite acceder al reporte de ventas.',
            'default_profiles' => ['Admin'],
            'route_names' => ['reports.sales'],
        ],
        'view.settings.offices' => [
            'name' => 'Ver consultorios',
            'group' => 'Configuraciones',
            'description' => 'Permite acceder al catalogo de consultorios.',
            'default_profiles' => ['Admin'],
            'route_names' => ['offices'],
        ],
        'view.settings.coupons' => [
            'name' => 'Ver cupones',
            'group' => 'Configuraciones',
            'description' => 'Permite acceder al catalogo de cupones.',
            'default_profiles' => ['Admin'],
            'route_names' => ['coupons'],
        ],
        'view.settings.services' => [
            'name' => 'Ver servicios',
            'group' => 'Configuraciones',
            'description' => 'Permite acceder al catalogo de servicios.',
            'default_profiles' => ['Admin'],
            'route_names' => ['services'],
        ],
        'view.settings.medications' => [
            'name' => 'Ver medicamentos',
            'group' => 'Configuraciones',
            'description' => 'Permite acceder al catalogo de medicamentos.',
            'default_profiles' => ['Admin'],
            'route_names' => ['medications'],
        ],
        'view.settings.specialties' => [
            'name' => 'Ver especialidades',
            'group' => 'Configuraciones',
            'description' => 'Permite acceder al catalogo de especialidades.',
            'default_profiles' => ['Admin'],
            'route_names' => ['specialties'],
        ],
        'view.settings.plans' => [
            'name' => 'Ver beneficios',
            'group' => 'Configuraciones',
            'description' => 'Permite acceder al catalogo de beneficios.',
            'default_profiles' => ['Admin'],
            'route_names' => ['plans'],
        ],
        'view.settings.whatsapp' => [
            'name' => 'Ver configuracion de WhatsApp',
            'group' => 'Configuraciones',
            'description' => 'Permite acceder a la configuracion de WhatsApp.',
            'default_profiles' => ['Admin'],
            'route_names' => ['settings.whatsapp'],
        ],
        'view.settings.legal' => [
            'name' => 'Ver configuracion legal',
            'group' => 'Configuraciones',
            'description' => 'Permite acceder a la configuracion de documentos legales.',
            'default_profiles' => ['Admin'],
            'route_names' => ['settings.legal'],
        ],
        'view.settings.parameters' => [
            'name' => 'Ver parametros',
            'group' => 'Configuraciones',
            'description' => 'Permite acceder a la administracion de parametros.',
            'default_profiles' => ['Admin'],
            'route_names' => ['settings.parameters'],
        ],
        'view.settings.permissions' => [
            'name' => 'Ver permisos',
            'group' => 'Configuraciones',
            'description' => 'Permite acceder a la administracion del catalogo de permisos.',
            'default_profiles' => ['Admin'],
            'route_names' => ['settings.permissions'],
        ],
        'view.clerk.medications' => [
            'name' => 'Ver medicamentos de mostrador',
            'group' => 'Mostrador',
            'description' => 'Permite acceder al catalogo de medicamentos para mostrador.',
            'default_profiles' => ['Clerk'],
            'route_names' => ['clerk.medications'],
        ],
        'view.clerk.dispensation' => [
            'name' => 'Ver surtido',
            'group' => 'Mostrador',
            'description' => 'Permite acceder al modulo de surtido.',
            'default_profiles' => ['Clerk'],
            'route_names' => ['clerk.dispensation'],
        ],
        'view.receptionist.policies' => [
            'name' => 'Ver membresias de recepcion',
            'group' => 'Recepcion',
            'description' => 'Permite acceder al listado de membresias para recepcion.',
            'default_profiles' => ['Receptionist'],
            'route_names' => ['recepcionist.policies'],
        ],
        'view.receptionist.requests' => [
            'name' => 'Ver solicitudes',
            'group' => 'Recepcion',
            'description' => 'Permite acceder al modulo de solicitudes de recepcion.',
            'default_profiles' => ['Receptionist'],
            'route_names' => ['receptionist.requests'],
        ],
        'view.receptionist.appointments' => [
            'name' => 'Ver check-out',
            'group' => 'Recepcion',
            'description' => 'Permite acceder al modulo de check-out.',
            'default_profiles' => ['Receptionist'],
            'route_names' => ['receptionist.appointments'],
        ],
        'view.receptionist.pending_results' => [
            'name' => 'Ver faltantes de resultados',
            'group' => 'Recepcion',
            'description' => 'Permite acceder al modulo de faltantes de resultados.',
            'default_profiles' => ['Receptionist'],
            'route_names' => ['receptionist.pending-results'],
        ],
        'view.doctor.home' => [
            'name' => 'Ver inicio de doctor',
            'group' => 'Doctor',
            'description' => 'Permite acceder al inicio del doctor.',
            'default_profiles' => ['Doctor'],
            'route_names' => ['doctor.home'],
        ],
        'view.doctor.history' => [
            'name' => 'Ver consultas',
            'group' => 'Doctor',
            'description' => 'Permite acceder al historial y consultas del doctor.',
            'default_profiles' => ['Doctor'],
            'route_names' => ['doctor.history'],
        ],
    ],
    'homes' => [
        'Admin' => [
            ['route' => 'dashboard', 'permission' => 'view.dashboard'],
            ['route' => 'preregistrations', 'permission' => 'view.admin.preregistrations'],
            ['route' => 'policies', 'permission' => 'view.admin.policies'],
            ['route' => 'appointments', 'permission' => 'view.admin.appointments'],
            ['route' => 'doctors', 'permission' => 'view.admin.doctors'],
            ['route' => 'users', 'permission' => 'view.admin.users'],
            ['route' => 'whatsapp.console', 'permission' => 'view.admin.whatsapp_console'],
            ['route' => 'reports.commissions', 'permission' => 'view.reports.commissions'],
            ['route' => 'reports.sales', 'permission' => 'view.reports.sales'],
            ['route' => 'offices', 'permission' => 'view.settings.offices'],
            ['route' => 'coupons', 'permission' => 'view.settings.coupons'],
            ['route' => 'services', 'permission' => 'view.settings.services'],
            ['route' => 'medications', 'permission' => 'view.settings.medications'],
            ['route' => 'specialties', 'permission' => 'view.settings.specialties'],
            ['route' => 'plans', 'permission' => 'view.settings.plans'],
            ['route' => 'settings.whatsapp', 'permission' => 'view.settings.whatsapp'],
            ['route' => 'settings.legal', 'permission' => 'view.settings.legal'],
            ['route' => 'settings.parameters', 'permission' => 'view.settings.parameters'],
            ['route' => 'settings.permissions', 'permission' => 'view.settings.permissions'],
        ],
        'Sales' => [
            ['route' => 'dashboard', 'permission' => 'view.dashboard'],
            ['route' => 'preregistrations', 'permission' => 'view.admin.preregistrations'],
            ['route' => 'policies', 'permission' => 'view.admin.policies'],
        ],
        'Clerk' => [
            ['route' => 'clerk.dispensation', 'permission' => 'view.clerk.dispensation'],
            ['route' => 'clerk.medications', 'permission' => 'view.clerk.medications'],
        ],
        'Receptionist' => [
            ['route' => 'receptionist.requests', 'permission' => 'view.receptionist.requests'],
            ['route' => 'recepcionist.policies', 'permission' => 'view.receptionist.policies'],
            ['route' => 'receptionist.appointments', 'permission' => 'view.receptionist.appointments'],
            ['route' => 'receptionist.pending-results', 'permission' => 'view.receptionist.pending_results'],
        ],
        'Doctor' => [
            ['route' => 'doctor.home', 'permission' => 'view.doctor.home'],
            ['route' => 'doctor.history', 'permission' => 'view.doctor.history'],
        ],
        'User' => [
            ['route' => 'user.home', 'permission' => null],
        ],
    ],
];
